### ISSUE TITLE
panic: unexpected attribute 'm'

### ISSUE THREAD

**Issue by jonasbark** [kjk/notionapi#9]
Hi!

I forked your version, adjusted the Page IDs and tried to download a page with subpages. 
I received the following error:

```
Page    1 ****: downloaded. Title: Development
Download **** failed with 'unexpected attribute 'm''
Download **** failed with 'unexpected attribute 'm''
panic: unexpected attribute 'm'

goroutine 1 [running]:
main.panicIfErr(...)
	/Users/boni/Documents/Programmieren/Web/Notion2Confluence/util.go:21
main.loadNotionPages(0xc000092340, 0x13d497e, 0x20, 0xc000130030, 0x1786000)
	/Users/boni/Documents/Programmieren/Web/Notion2Confluence/import.go:381 +0x47c
main.loadAllPages(0xc000092340, 0xc0005d1df8, 0x1, 0x1, 0xc00001a000, 0xc00012e108)
	/Users/boni/Documents/Programmieren/Web/Notion2Confluence/import.go:395 +0xb0
main.loadArticles(0xc000092340, 0x1dcee7)
```

Looking at the log I think it might be the discussion + comments that are on one of those pages:
```
 "discussion": {
      "a70a81be-6ab5-4a87-b716-c79624f8adb8": {
        "role": "editor",
        "value": {
          "comments": [
            "a087e43b-cc18-4843-9e02-8e330c17627d",
            "0f769e08-4642-4df8-92d7-874dd7627a8f"
          ],
          "context": [
            [
              "TODO",
              [
                [
                  "m",
                  "a70a81be-6ab5-4a87-b716-c79624f8adb8"
                ]
              ]
            ]
          ],
          "id": "a70a81be-6ab5-4a87-b716-c79624f8adb8",
          "parent_id": "098cc82b-fa71-4746-b67b-26e618192526",
          "parent_table": "block",
          "resolved": false,
          "version": 2
        }
      }
    },
```

**Comment by kjk** [comment]
Thanks for the report, should be fixed now.

If you still have problems, please make the page that causes issues public let me know the id of the page so that I can test with it.
